Repository bcgov/digital.gov.bc.ca, pull requests merged in 2020-06, with the labels that each got.

#79 Feature 51
  .env.example
  docker-compose.yml
  react-frontend/.env.example
  react-frontend/package-lock.json
  react-frontend/package.json
  react-frontend/src/App.css
  react-frontend/src/App.js
  react-frontend/src/App.test.js
  react-frontend/src/components/Nav/index.js
  react-frontend/src/components/Query/index.js
  react-frontend/src/containers/App/index.js
  react-frontend/src/index.css
  react-frontend/src/index.js
  react-frontend/src/logo.svg
  react-frontend/src/queries/catagory/catagories.js
  react-frontend/src/serviceWorker.js
  react-frontend/src/setupTests.js
  react-frontend/src/utils/apolloClient.js
  strapi-app/api/article/config/routes.json
  strapi-app/api/article/controllers/article.js
  strapi-app/api/article/models/article.js
  strapi-app/api/article/models/article.settings.json
  strapi-app/api/article/services/article.js
  strapi-app/api/category/config/routes.json
  strapi-app/api/category/controllers/category.js
  strapi-app/api/category/models/category.js
  strapi-app/api/category/models/category.settings.json
  strapi-app/api/category/services/category.js
  strapi-app/package.json
  strapi-app/yarn.lock
Labels: READY FOR REVIEW

#73 Feature 52
  react-frontend/.eslintignore
  react-frontend/.eslintrc
  react-frontend/.prettierignore
  react-frontend/.prettierrc
  react-frontend/package-lock.json
  react-frontend/package.json
  react-frontend/src/App.test.js
  react-frontend/src/components/Nav/index.js
  react-frontend/src/components/Query/index.js
  react-frontend/src/containers/App/index.js
  react-frontend/src/index.js
  react-frontend/src/queries/catagory/catagories.js
  react-frontend/src/serviceWorker.js
  react-frontend/src/setupTests.js
  react-frontend/src/utils/apolloClient.js
  strapi-app/.eslintignore
  strapi-app/.eslintrc
Labels: enhancement, task: dev

#95 Feature 80
  docker-compose.yml
  react-frontend/.env.example
  react-frontend/Dockerfile
  react-frontend/package-lock.json
  react-frontend/package.json
  react-frontend/src/utils/apolloClient.js
Labels: READY FOR REVIEW

#77 Feature 38/optimize infra
  openshift/README.md
  openshift/ansible/build-react.yaml
  openshift/ansible/deploy-react.yaml
  openshift/ansible/group_vars/all/vars.yaml
  openshift/templates/README.md
  openshift/templates/react-frontend/README.md
  openshift/templates/react-frontend/bc.yaml
  openshift/templates/react-frontend/build.param
  openshift/templates/react-frontend/dc.yaml
  openshift/templates/react-frontend/deploy.param
Labels: task: devops

#117 added navbar placeholder and replaced images with simpler ones
  react-frontend/src/components/Home/cardlist.js
  react-frontend/src/components/Home/home.js
  react-frontend/src/components/Nav/footer.js
  react-frontend/src/components/Nav/navbar.js
  react-frontend/src/containers/App/index.js
  react-frontend/src/css/footer.css
  react-frontend/src/css/home.css
  react-frontend/src/css/nav.css
  react-frontend/src/css/pageheader.css
  react-frontend/src/images/logo-banner.png
  react-frontend/src/images/logo.svg
Labels: READY FOR REVIEW

#116 Pipeline/infra improvements
  .gitignore
  openshift/README.md
  openshift/ansible/build-react.yaml
  openshift/ansible/deploy-react.yaml
  openshift/ansible/group_vars/all/vars.yaml
  openshift/ansible/promote-environment.yaml
  openshift/ansible/rollback-react.yaml
  openshift/ansible/tasks/build_react.yaml
  openshift/ansible/tasks/check_image_exists.yaml
  openshift/ansible/tasks/check_pr_exists.yaml
  openshift/ansible/tasks/deploy_react.yaml
  openshift/ansible/templates/build.param.j2
  openshift/ansible/templates/deploy.param.j2
  openshift/ansible/templates/pr_tag.j2
  openshift/templates/react-frontend/README.md
  openshift/templates/react-frontend/bc.yaml
  openshift/templates/react-frontend/build.param
  openshift/templates/react-frontend/dc.yaml
  openshift/templates/react-frontend/deploy.param
Labels: READY FOR REVIEW, task: devops

#125 Feature 82
  react-frontend/package-lock.json
  react-frontend/package.json
  react-frontend/public/index.html
  react-frontend/src/components/Nav/footer.js
  react-frontend/src/components/Nav/navbar.js
  react-frontend/src/components/Resources/digitalcards.js
  react-frontend/src/components/Resources/fordesigners.js
  react-frontend/src/components/Resources/fordevelopers.js
  react-frontend/src/components/Resources/guides.js
  react-frontend/src/components/Resources/resourceheader.js
  react-frontend/src/components/Resources/resources.js
  react-frontend/src/components/Resources/standards.js
  react-frontend/src/containers/App/index.js
  react-frontend/src/css/card.css
  react-frontend/src/css/home.css
  react-frontend/src/css/nav.css
  react-frontend/src/css/resources.css
  react-frontend/src/index.js
Labels: READY FOR REVIEW

#124 Github Actions CD pipeline to dev
  .github/secrets.yaml
  .github/workflows/deploy-to-dev.yaml
  openshift/README.md
  openshift/ansible/build-react.yaml
  openshift/ansible/create-gh-deployment.yaml
  openshift/ansible/group_vars/all/vars.yaml
  openshift/ansible/oc-login.yaml
  openshift/ansible/tasks/build_react.yaml
  openshift/ansible/tasks/cancel_previous_gh_deployments.yaml
  openshift/ansible/tasks/check_if_should_build.yaml
  openshift/ansible/tasks/deploy_react.yaml
  openshift/ansible/tasks/wait_for_rollout.yaml
  openshift/ansible/templates/github_deployment.json.j2
  openshift/docs/deployment-automation.md
  openshift/templates/cicd.yaml
  openshift/templates/react-frontend/bc.yaml
Labels: READY FOR REVIEW, task: dev, task: devops
